# Generated by Django 3.1.6 on 2021-02-22 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210221_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=150),
        ),
    ]
